### ISSUE TITLE
userKeysFlushInterval field is not properly set via LDConfig.Builder

### ISSUE THREAD

**Issue by kutsal** [launchdarkly/java-server-sdk#162]
**Describe the bug**
`userKeysFlushInterval` field is not properly set via `LDConfig.Builder`

**To reproduce**
Set it to a value other than the default and observe it not take effect.

**Expected behavior**
`LDClient` uses the value I set via the builder.

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
4.6.3

**Language version, developer tools**
Java 8

**OS/platform**
RHEL 7, OSX Mojave

**Additional context**
[Offending line of code.](https://github.com/launchdarkly/java-server-sdk/blob/5bb05d41c66df00f92866bb75d17e1f125755df9/src/main/java/com/launchdarkly/client/LDConfig.java#L544)

**Comment by eli-darkly** [comment]
Thanks for catching this. Should be a quick fix.

**Comment by kutsal** [comment]
Indeed. I just submitted PR #163 that fixes this.
