### ISSUE TITLE
Typo in https://github.com/launchdarkly/java-server-sdk/blob/master/src/main/java/com/launchdarkly/sdk/server/EventBroadcasterImpl.java#L93

### ISSUE THREAD

**Issue by andrewwilsonnew** [launchdarkly/java-server-sdk#211]
**Is this a support request?**
No

**Describe the bug**
Typo in https://github.com/launchdarkly/java-server-sdk/blob/master/src/main/java/com/launchdarkly/sdk/server/EventBroadcasterImpl.java#L93

Currently reads :
          Loggers.MAIN.warn("Unexpected error from listener ({0}): {1}", l.getClass(), e.toString());

Should read:
          Loggers.MAIN.warn("Unexpected error from listener ({}): {}", l.getClass(), e.toString());

**To reproduce**
Generate an exception from the listener

**Expected behavior**
The message should be correctly logged

**Logs**
[LaunchDarkly-tasks-0] WARN com.launchdarkly.sdk.server.LDClient - Unexpected error from listener ({0}): {1}

**SDK version**
5.0.3

**Language version, developer tools**
Java

**OS/platform**
Mac

**Additional context**
I think this is just a clear typo and should be fixed.

**Comment by gwhelanLD** [comment]
Hi @andrewwilsonnew,

Thanks for the report, I've filed it internally (ch89935). We'll include this change in the next patch release.

Thanks!
@gwhelanLD

**Comment by eli-darkly** [comment]
Fixed in the 5.1.1 release.
