### ISSUE TITLE
TestData FlagBuilder rules seem to be erased when toggling a flag off and on again

### ISSUE THREAD

**Issue by ashoofly** [launchdarkly/java-server-sdk#220]
**Is this a support request?**
Yes and no? I filed a support ticket since it affects our work but source seems to be SDK itself. 

**Describe the bug**
The TestData source does not seem to persist rules after toggling a flag off and then back on again.

**To reproduce**
Run these added unit tests: https://github.com/ashoofly/java-server-sdk/pull/1/files.
`rulesPersistAfterTogglingFlagOffAndOn()` should fail.
For comparison, `targetsPersistAfterTogglingFlagOffAndOn()` succeeds.

**Expected behavior**
Existing rules should remain in place after a flag is toggled back on. 

**Logs**

**SDK version**
5.2.0

**Language version, developer tools**
jdk1.8.0_121

**OS/platform**
Mac OSX Catalina

**Additional context**
I've also noticed during debugging that the `rules` field in the `TestData.FlagBuilder` is always `null`.

**Comment by bwoskow-ld** [comment]
Hi @ashoofly ,

Thanks for letting us know! Indeed, targeting rules aren't copied to new `FlagBuilder` instances which are created when the test data is updated. This is a bug and I have a fix for it under review internally.

Cheers,
Ben

**Comment by bwoskow-ld** [comment]
Hi @ashoofly,

We've released [5.2.1](https://github.com/launchdarkly/java-server-sdk/releases/tag/5.2.1) with a fix.

Cheers,
Ben

**Comment by ashoofly** [comment]
Thank you, @bwoskow-ld!
