### ISSUE TITLE
Delete user feature

### ISSUE THREAD

**Issue by eugeneastashevich** [launchdarkly/java-server-sdk#246]
Hi guys! A quick question - do you plan to support [`delete user`](https://apidocs.launchdarkly.com/reference#delete-user) feature in Java SDK? Is it on your roadmap for the current year?

**Comment by netroy** [comment]
I'd like to know this as well.  
We need to be able to delete user profiles when we delete accounts, to comply with data-retention laws.

**Comment by bwoskow-ld** [comment]
Hi @eugeneastashevich,

I have to redirect you to LaunchDarkly support. This issue tracker is specific for the Java SDK and this question is about a more general feature request affecting the whole system. The support team will be able to answer your question. Click "contact support" at https://support.launchdarkly.com.

Cheers,
@bwoskow-ld

**Comment by eugeneastashevich** [comment]
Hi @bwoskow-ld,

But this feature is supported in LaunchDarkly API: https://apidocs.launchdarkly.com/reference#delete-user, so it's not a general feature request. I just need it to be supported in Java SDK.

**Comment by eli-darkly** [comment]
@eugeneastashevich The Java SDK isn't a client for any of the APIs described in https://apidocs.launchdarkly.com. It's the SDK for evaluating feature flags. What you want is https://github.com/launchdarkly/api-client-java.

**Comment by bwoskow-ld** [comment]
Also, to piggy-back off of @eli-darkly's response -- we plan on adding support for the delete user API, and many others which are currently missing, in the next week or so. Watch [that repository](https://github.com/launchdarkly/api-client-java) for updates.

**Comment by eugeneastashevich** [comment]
Guys, thanks for the clarification!
