### ISSUE TITLE
SDK keeps trying to post diagnostics, even when using invalid sdk key

### ISSUE THREAD

**Issue by frederikvanhoyweghen** [launchdarkly/java-server-sdk#250]
**Is this a support request?**
No

**Describe the bug**
When using an invalid SDK key, LDClient will keep trying to post diagnostic events even when it's supposed to stop trying after x amount of failed attempts.

**To reproduce**
- Initialize an LDClient with an invalid SDK key
- Perform some LD API operations using the LDClient. Not sure about any additional required steps - this has happened right from the start of our implementation.

**Expected behavior**
No more attempts to post diagnostics after repeated failures due to invalid SDK key

**Logs**
![afbeelding](https://user-images.githubusercontent.com/18288079/144817442-d960b9cc-c61d-4d76-a6cb-b23e76589820.png)

**SDK version**
5.6.3

**Language version, developer tools**
Java 8

**OS/platform**
Observed on Windows 10, Debian Buster

**Comment by eli-darkly** [comment]
Thanks for reporting this. The problem seems clear and we're working on a fix.

**Comment by eli-darkly** [comment]
_(Filed internally as 133942)_

**Comment by eli-darkly** [comment]
This is fixed in version [5.6.5](https://github.com/launchdarkly/java-server-sdk/releases/tag/5.6.5).
