### ISSUE TITLE
Getting numerous Error posting diagnostic event (giving up permanently): HTTP error 401 (invalid SDK key)

### ISSUE THREAD

**Issue by MVran** [launchdarkly/java-server-sdk#269]
After init code part
```
 if self.client.get().is_initialized():
            logger.info("Launch Darkly SDK successfully initialized.")
```
I get  "Launch Darkly SDK successfully initialized."
I've double checked sdk key and it's right as well as reading flags.
Confg is simple containing only sdk key.       
`self.client.set_config(Config(sdk_key))`
**Logs**
I have started getting 
_Error posting diagnostic event (giving up permanently): HTTP error 401 (invalid SDK key)_
Deployment is on kubernetes with multiple pods, and framework is Flask, it some race condition happening here?
Note that in local I am not getting this message.

**SDK version**
launchdarkly-server-sdk = "^7.4.2"

**Language version, developer tools**
python 3.9

**OS/platform**
For instance, Ubuntu 16.04

**Comment by eli-darkly** [comment]
@MVran Did you mean to post this in https://github.com/launchdarkly/python-server-sdk rather than in the Java SDK project?

**Comment by MVran** [comment]
Moved issue to   https://github.com/launchdarkly/python-server-sdk.
