### ISSUE TITLE
fat jar brings in duplicate copy of `launchdarkly-logging`

### ISSUE THREAD

**Issue by bplommer** [launchdarkly/java-server-sdk#282]
**Describe the bug**
The fat jar contains a copy of the `launchdarkly-logging` library but *also* introduces a transitive dependency on a separate jar of that library, resulting in duplicates on the classpath - see screenshot from IntelliJ below.

<img width="436" alt="Screenshot 2022-10-04 at 17 19 49" src="https://user-images.githubusercontent.com/8990749/195323940-4fb5bac2-21f1-425a-9453-0d5d55ee74b3.png">

**Expected behavior**
The jar should either contain the logging library or introduce a dependency on a separate jar, but not both.

**Comment by eli-darkly** [comment]
Thanks for catching this. The intention is for that library _not_ to be present in the jar, and there was supposed to be a build step to double-check that there are no such duplicated classes, but clearly something went wrong. We should be able to fix this pretty quickly.

**Comment by eli-darkly** [comment]
Sorry for the delay in releasing this patch. The [5.10.3](https://github.com/launchdarkly/java-server-sdk/releases/tag/5.10.2) release removes the redundant dependency.

**Comment by eli-darkly** [comment]
I'm going to go ahead and close the issue, but please reopen it if you find that this did not solve the problem.
